export enum DataType {
  HOME_TITLE = "home_title",
  // HOME_BANNER = "home_banner",
  // HOME_SLIDER = "home_slider",
  ABOUT_TITLE = "about_title",
  // ABOUT_DESCRIPTION = "about_description",
  SOCIAL_MEDIA = "social_media",
  PORTFOLIA_ITEM = "portfolia_item",
  // PORTFOLIA_TITLE = "portfolia_title",
  // LOGO = "logo",
  // SITE_MUSIC = "site_music",
  // SERVICE_TITLE = "service_title",
  SERVICE_ITEM = "service_item",
  CONTACT_THEME = "contact_theme",
  SERVICE_SLIDE = "service_slide",
}
